quant:
    a_qconfig:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 4
        symmetric: False
        ch_axis: -1
    w_qconfig:
        quantizer: AdaRoundFakeQuantize
        observer: MSEObserver
        bit: 2
        symmetric: False
        ch_axis: 0
    calibrate: 1024
    recon:
        batch_size: 32
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.01
        iters: 20000
        b_range: [20, 2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        drop_prob: 0.5
model:                    # architecture details
    type: regnetx_600m        # model name
    path: /mnt/lustre/weixiuying/model_zoo/regnet_600m.pth.tar
data:
    path: /mnt/lustre/share/ImageNet-Pytorch/
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005
